/** Generated by scripts/build-vehicle-catalog.ts. Do not edit by hand. */
export const CATALOG_VERSION = "catalog-2026-09-21"
export const CATALOG_RETRIEVED_ON = "2026-09-21"
export const CATALOG_REFRESH_AFTER = "2027-03-20"
export const CATALOG_YEAR_MIN = 2006
export const CATALOG_YEAR_MAX = 2027
export const CATALOG_TERMS = "Retrieved 21 September 2026. NHTSA vPIC (https://vpic.nhtsa.dot.gov/api/) is the manufacturer-submitted vehicle listing. Callers are subject to NHTSA’s automated rate control. This snapshot requests passenger car, truck, and multipurpose passenger vehicle models only and stores no VINs. FuelEconomy.gov vehicles.csv (https://www.fueleconomy.gov/feg/epadata/vehicles.csv) is the DOE and EPA fuel-economy file, described at https://www.fueleconomy.gov/feg/ws/index.shtml. This snapshot keeps year, make, base model, and model name. It does not keep fuel-cost or economy figures. Both are U.S. government public datasets, copied in this reduced form. Names the sources did not print were not added as trims."
export const NHTSA_CATALOG_URL = "https://vpic.nhtsa.dot.gov/api/vehicles/GetModelsForMakeIdYear/"
export const FUEL_ECONOMY_CATALOG_URL = "https://www.fueleconomy.gov/feg/epadata/vehicles.csv"
export const FUEL_ECONOMY_DOCS_URL = "https://www.fueleconomy.gov/feg/ws/index.shtml"
