/** Generated by scripts/build-vehicle-catalog.ts. Do not edit by hand. */
export const CATALOG_DEFAULTS = {
  molly: { year: 2023, make: "Ford", model: "F-150", trim: "F150 Pickup 4WD" },
  jayden: { year: 2023, make: "Toyota", model: "RAV4", trim: "RAV4" },
  ava: { year: 2023, make: "Tesla", model: "Model Y", trim: "Model Y Long Range AWD" },
} as const
